# Generated by Django 5.2.7 on 2025-10-14 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('school_class', models.CharField(blank=True, max_length=10, null=True)),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('course_year', models.CharField(blank=True, max_length=10, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('study_hours', models.FloatField(blank=True, null=True)),
                ('attendance', models.FloatField(blank=True, null=True)),
                ('internal_marks', models.FloatField(blank=True, null=True)),
                ('assignments_completed', models.IntegerField(blank=True, null=True)),
                ('predicted_grade', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
