# Generated by Django 5.2.7 on 2025-10-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_profile_phone_profile_profile_pic_profile_roll_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default_profile.png', upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roll_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
