# Generated by Django 5.2.7 on 2025-10-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_remove_profile_profile_picture_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
