# Generated by Django 5.2.7 on 2025-10-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0007_libraryfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(choices=[('UP', 'UP Board'), ('CBSE', 'CBSE'), ('ICSE', 'ICSE')], max_length=10)),
                ('class_name', models.CharField(choices=[('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('syllabus_title', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='libraryfile',
            old_name='uploaded_at',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='libraryfile',
            name='file',
        ),
        migrations.AddField(
            model_name='libraryfile',
            name='file_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libraryfile',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
            preserve_default=False,
        ),
    ]
