# Generated by Django 5.2.7 on 2025-10-31 15:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0008_syllabus_rename_uploaded_at_libraryfile_date_added_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.CharField(max_length=255)),
                ('board', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='pyq_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('syllabus', 'Syllabus'), ('pyq', 'Previous Year Question')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resources/')),
            ],
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='file_url',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='syllabus_files/'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='board',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='class_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='syllabus_title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predictor.paper')),
                ('syllabus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predictor.syllabus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
